import './css/globals.css'
import toast, { Toaster } from 'react-hot-toast';
import Header from '@/components/header/Header'
import Footer from '@/components/footer/Footer'

export const metadata = {
  title: 'Bcom Loan App',
  description: 'Generated by create next app',
}


export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <div className='main-container'>
          <Header/>
          {children}
          <Footer/>
        </div>

        <Toaster />
      </body>
    </html>
  )
}
